### ISSUE TITLE
pathlib.Path cannot be directly derived

### ISSUE THREAD

**Issue by oesteban** [nipype/pydra#172]
```
$ python -c "from pydra.engine.specs import File; File('some/path')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/oesteban/.anaconda3/lib/python3.7/pathlib.py", line 1003, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/oesteban/.anaconda3/lib/python3.7/pathlib.py", line 658, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/oesteban/.anaconda3/lib/python3.7/pathlib.py", line 651, in _parse_args
    return cls._flavour.parse_parts(parts)
AttributeError: type object 'File' has no attribute '_flavour'
```

**Comment by satra** [comment]
i think i know why we are not seeing any error. the File is only used for type annotation, and has no other role in a dataclass. so we are actually never initializing it even!
