### ISSUE TITLE
error in handling inner exceptions of tasks in a workflow

### ISSUE THREAD

**Issue by satra** [nipype/pydra#299]
i know i merged #290 , but this requires more tests where inner tasks of a workflow crash and raise an exception and then the output is used downstream in another task

@djarecka and @nicolocin  - this may require you to communicate a bit so that this knowledge is shared. we have to do a better job of exception handling. this is one reason i didn't like pyspark despite it's other advantages. 

```
wf
  taska_with_splits (one split crashes)
  taskb_with_inputs_from_taska (doesn't handle exception properly)
```

see the last 4 lines of the stacktrace below

<details> <summary> Full traceback </summary>

```
2020-06-23 08:26:10,934 [   ERROR] Task exception was never retrieved
future: <Task finished name='Task-18' coro=<ConcurrentFuturesWorker.exec_as_coro() done, defined at /Users/satra/software/pydra/pydra/pydra/engine/workers.py:197> exception=TypeError('type object argument after * must be an iterable, not DecisionTreeClassifier', ' full crash report is here: /Users/satra/software/pydra/pydra-ml/test/cache-wf/FunctionTask_3e13ca9a7dacbfc9e8945177ffd6920aaf48f0436e89d39bf6709fca691a3305/_error.pklz')>
concurrent.futures.process._RemoteTraceback: 
"""
TypeError: type object argument after * must be an iterable, not DecisionTreeClassifier

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/satra/software/miniconda3/envs/mee-voice/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/satra/software/pydra/pydra/pydra/engine/helpers.py", line 575, in load_and_run
    raise type(excinfo)(
TypeError: ('type object argument after * must be an iterable, not DecisionTreeClassifier', ' full crash report is here: /Users/satra/software/pydra/pydra-ml/test/cache-wf/FunctionTask_3e13ca9a7dacbfc9e8945177ffd6920aaf48f0436e89d39bf6709fca691a3305/_error.pklz')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/satra/software/pydra/pydra/pydra/engine/workers.py", line 203, in exec_as_coro
    res = await self.loop.run_in_executor(
TypeError: ('type object argument after * must be an iterable, not DecisionTreeClassifier', ' full crash report is here: /Users/satra/software/pydra/pydra-ml/test/cache-wf/FunctionTask_3e13ca9a7dacbfc9e8945177ffd6920aaf48f0436e89d39bf6709fca691a3305/_error.pklz')
2020-06-23 08:26:11,064 [   ERROR] Task exception was never retrieved
future: <Task finished name='Task-19' coro=<ConcurrentFuturesWorker.exec_as_coro() done, defined at /Users/satra/software/pydra/pydra/pydra/engine/workers.py:197> exception=TypeError('type object argument after * must be an iterable, not DecisionTreeClassifier', ' full crash report is here: /Users/satra/software/pydra/pydra-ml/test/cache-wf/FunctionTask_576a6c8c5d766a613bea5b618bf82cdac32d9ce08c935b73a9d9e9c120bc9574/_error.pklz')>
concurrent.futures.process._RemoteTraceback: 
"""
TypeError: type object argument after * must be an iterable, not DecisionTreeClassifier

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/satra/software/miniconda3/envs/mee-voice/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/satra/software/pydra/pydra/pydra/engine/helpers.py", line 575, in load_and_run
    raise type(excinfo)(
TypeError: ('type object argument after * must be an iterable, not DecisionTreeClassifier', ' full crash report is here: /Users/satra/software/pydra/pydra-ml/test/cache-wf/FunctionTask_576a6c8c5d766a613bea5b618bf82cdac32d9ce08c935b73a9d9e9c120bc9574/_error.pklz')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/satra/software/pydra/pydra/pydra/engine/workers.py", line 203, in exec_as_coro
    res = await self.loop.run_in_executor(
TypeError: ('type object argument after * must be an iterable, not DecisionTreeClassifier', ' full crash report is here: /Users/satra/software/pydra/pydra-ml/test/cache-wf/FunctionTask_576a6c8c5d766a613bea5b618bf82cdac32d9ce08c935b73a9d9e9c120bc9574/_error.pklz')
Traceback (most recent call last):
  File "/Users/satra/software/miniconda3/envs/mee-voice/bin/pydraml", line 11, in <module>
    load_entry_point('pydra-ml', 'console_scripts', 'pydraml')()
  File "/Users/satra/software/miniconda3/envs/mee-voice/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/satra/software/miniconda3/envs/mee-voice/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/satra/software/miniconda3/envs/mee-voice/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/satra/software/miniconda3/envs/mee-voice/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/satra/software/pydra/pydra-ml/pydra_ml/cli.py", line 48, in main
    run_workflow(wf, plugin[0], plugin_args, specfile)
  File "/Users/satra/software/pydra/pydra-ml/pydra_ml/classifier.py", line 115, in run_workflow
    sub(runnable=wf)
  File "/Users/satra/software/pydra/pydra/pydra/engine/submitter.py", line 59, in __call__
    self.loop.run_until_complete(self.submit(runnable, wait=True, rerun=rerun))
  File "/Users/satra/software/miniconda3/envs/mee-voice/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/Users/satra/software/pydra/pydra/pydra/engine/submitter.py", line 133, in submit
    await asyncio.gather(*futures)
  File "/Users/satra/software/pydra/pydra/pydra/engine/submitter.py", line 79, in submit_workflow
    await load_and_run_async(
  File "/Users/satra/software/pydra/pydra/pydra/engine/helpers.py", line 588, in load_and_run_async
    await task._run(submitter=submitter, rerun=rerun, **kwargs)
  File "/Users/satra/software/pydra/pydra/pydra/engine/core.py", line 918, in _run
    await self._run_task(submitter, rerun=rerun)
  File "/Users/satra/software/pydra/pydra/pydra/engine/core.py", line 936, in _run_task
    await submitter._run_workflow(self, rerun=rerun)
  File "/Users/satra/software/pydra/pydra/pydra/engine/submitter.py", line 166, in _run_workflow
    task.inputs.retrieve_values(wf)
  File "/Users/satra/software/pydra/pydra/pydra/engine/specs.py", line 68, in retrieve_values
    value = value.get_value(wf, state_index=state_index)
  File "/Users/satra/software/pydra/pydra/pydra/engine/specs.py", line 507, in get_value
    return [getattr(res.output, self.field) for res in result]
  File "/Users/satra/software/pydra/pydra/pydra/engine/specs.py", line 507, in <listcomp>
    return [getattr(res.output, self.field) for res in result]
AttributeError: 'NoneType' object has no attribute 'output'
```
</details>

**Comment by djarecka** [comment]
closed with #303
