### ISSUE TITLE
Caching error with nested workflow on SLURM clusters

### ISSUE THREAD

**Issue by nicolocin** [nipype/pydra#368]
Was working on #366 and found out that nested workflow tests that pass in the SLURM CI (that runs in a docker container) won't work on Openmind.   This is with the most recent commit b52a05b and specifying `tmpdir` when running pytest.

For example, for `test_wf_in_wf` in `test_submitter.py` 
```python
def test_wf_in_wf(plugin):
    """WF(A --> SUBWF(A --> B) --> B)"""
    wf = Workflow(name="wf_in_wf", input_spec=["x"])
    wf.inputs.x = 3
    wf.add(sleep_add_one(name="wf_a", x=wf.lzin.x))

    # workflow task
    subwf = Workflow(name="sub_wf", input_spec=["x"])
    subwf.add(sleep_add_one(name="sub_a", x=subwf.lzin.x))
    subwf.add(sleep_add_one(name="sub_b", x=subwf.sub_a.lzout.out))
    subwf.set_output([("out", subwf.sub_b.lzout.out)])
    # connect, then add
    subwf.inputs.x = wf.wf_a.lzout.out
    wf.add(subwf)

    wf.add(sleep_add_one(name="wf_b", x=wf.sub_wf.lzout.out))
    wf.set_output([("out", wf.wf_b.lzout.out)])

    with Submitter(plugin) as sub:
        sub(wf)

    res = wf.result()
    assert res.output.out == 7

```

All of the options give following gives the same error on Openmind

1. Not specifying cache_dir for both `wf` and `subwf` (aka the unmodified code above)

2. `cache_dir=tmpdir` for both `wf` and `subwf`
```python
def test_wf_in_wf2(plugin, tmpdir):
    """WF(A --> SUBWF(A --> B) --> B)"""
    wf = Workflow(name="wf_in_wf", input_spec=["x"], cache_dir=tmpdir)
    ....

    subwf = Workflow(name="sub_wf", input_spec=["x"], cache_dir=tmpdir)
    ....

```

3. Different `cache_dir`
```python
def test_wf_in_wf2(plugin, tmpdir):
    """WF(A --> SUBWF(A --> B) --> B)"""
    cache_dir1 = tmpdir.mkdir("test_wf_in_wf1")
    cache_dir2 = tmpdir.mkdir("test_wf_in_wf2")
    wf = Workflow(name="wf_in_wf", input_spec=["x"], cache_dir=cache_dir1)
    ....

    subwf = Workflow(name="sub_wf", input_spec=["x"], cache_dir=cache_dir2)
    ....

```

4. Different `cache_dir` with `cache_locations`
```python
def test_wf_in_wf2(plugin, tmpdir):
    """WF(A --> SUBWF(A --> B) --> B)"""
    cache_dir1 = tmpdir.mkdir("test_wf_in_wf1")
    cache_dir2 = tmpdir.mkdir("test_wf_in_wf2")
    wf = Workflow(name="wf_in_wf", input_spec=["x"], cache_dir=cache_dir1, cache_locations=cache_dir2)
    ....

    subwf = Workflow(name="sub_wf", input_spec=["x"], cache_dir=cache_dir2, cache_locations=cache_dir1)
    ....

```

Common error:
```python

nlo[09:35][2.88][-49%]nlo@openmind7:nipype-pydra$ pytest -vvs --basetemp=/scratch/Thu/nlo/tmpdir pydra/engine/tests/test_submitter.py::test_wf_in_wf
============================================================================== test session starts ===============================================================================
platform linux -- Python 3.7.7, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /om2/user/nlo/miniconda/envs/pydra/bin/python3.7
cachedir: .pytest_cache
rootdir: /home/nlo/scripts/nipype-pydra
plugins: cov-2.10.1, env-0.6.2, forked-1.3.0, rerunfailures-9.1.1, xdist-1.34.0
collected 1 item

pydra/engine/tests/test_submitter.py::test_wf_in_wf[slurm] FAILED

==================================================================================== FAILURES ====================================================================================
______________________________________________________________________________ test_wf_in_wf[slurm] ______________________________________________________________________________

plugin = 'slurm', tmpdir = local('/net/vast-storage.ib.cluster/scratch/Thu/nlo/tmpdir/test_wf_in_wf_slurm_0')

    def test_wf_in_wf(plugin, tmpdir):
        """WF(A --> SUBWF(A --> B) --> B)"""
        #cache_dir1 = tmpdir.mkdir("test_wf_in_wf1")
        #cache_dir2 = tmpdir.mkdir("test_wf_in_wf2")
        wf = Workflow(name="wf_in_wf", input_spec=["x"], cache_dir=tmpdir)
        wf.inputs.x = 3
        wf.add(sleep_add_one(name="wf_a", x=wf.lzin.x))

        # workflow task
        subwf = Workflow(name="sub_wf", input_spec=["x"], cache_dir=tmpdir)
        subwf.add(sleep_add_one(name="sub_a", x=subwf.lzin.x))
        subwf.add(sleep_add_one(name="sub_b", x=subwf.sub_a.lzout.out))
        subwf.set_output([("out", subwf.sub_b.lzout.out)])
        # connect, then add
        subwf.inputs.x = wf.wf_a.lzout.out

        wf.add(subwf)
        wf.add(sleep_add_one(name="wf_b", x=wf.sub_wf.lzout.out))
        wf.set_output([("out", wf.wf_b.lzout.out)])

        with Submitter(plugin) as sub:
>           sub(wf)

pydra/engine/tests/test_submitter.py:108:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pydra/engine/submitter.py:57: in __call__
    self.loop.run_until_complete(self.submit_workflow(runnable, rerun=rerun))
/om2/user/nlo/miniconda/envs/pydra/lib/python3.7/asyncio/base_events.py:587: in run_until_complete
    return future.result()
pydra/engine/submitter.py:72: in submit_workflow
    await workflow._run(self, rerun=rerun)
pydra/engine/core.py:969: in _run
    await self._run_task(submitter, rerun=rerun)
pydra/engine/core.py:988: in _run_task
    await submitter._run_workflow(self, rerun=rerun)
pydra/engine/submitter.py:170: in _run_workflow
    await self.submit_workflow(task, rerun=rerun)
pydra/engine/submitter.py:72: in submit_workflow
    await workflow._run(self, rerun=rerun)
pydra/engine/core.py:970: in _run
    result.output = self._collect_outputs()
pydra/engine/core.py:1052: in _collect_outputs
    val_out = val.get_value(self)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = LF('sub_b', 'out'), wf = <pydra.engine.core.Workflow object at 0x2b28d850d450>, state_index = None

    def get_value(self, wf, state_index=None):
        """Return the value of a lazy field."""
        if self.attr_type == "input":
            return getattr(wf.inputs, self.field)
        elif self.attr_type == "output":
            node = getattr(wf, self.name)
            result = node.result(state_index=state_index)
            if isinstance(result, list):
                if len(result) and isinstance(result[0], list):
                    results_new = []
                    for res_l in result:
                        res_l_new = []
                        for res in res_l:
                            if res.errored:
                                raise ValueError("Error from get_value")
                            else:
                                res_l_new.append(res.get_output_field(self.field))
                        results_new.append(res_l_new)
                    return results_new
                else:
                    results_new = []
                    for res in result:
                        if res.errored:
                            raise ValueError("Error from get_value")
                        else:
                            results_new.append(res.get_output_field(self.field))
                    return results_new
            else:
>               if result.errored:
E               AttributeError: 'NoneType' object has no attribute 'errored'

pydra/engine/specs.py:697: AttributeError
------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------
ERROR    asyncio:base_events.py:1619 Task exception was never retrieved
future: <Task finished coro=<SlurmWorker._submit_job() done, defined at /home/nlo/scripts/nipype-pydra/pydra/engine/workers.py:263> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/nlo/scripts/nipype-pydra/pydra/engine/workers.py", line 301, in _submit_job
    done = await self._poll_job(jobid)
  File "/home/nlo/scripts/nipype-pydra/pydra/engine/workers.py", line 322, in _poll_job
    status = await self._verify_exit_code(jobid)
  File "/home/nlo/scripts/nipype-pydra/pydra/engine/workers.py", line 340, in _verify_exit_code
    error_line = Path(error_file).read_text().split("\n")[-2]
  File "/om2/user/nlo/miniconda/envs/pydra/lib/python3.7/pathlib.py", line 1216, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/om2/user/nlo/miniconda/envs/pydra/lib/python3.7/pathlib.py", line 1203, in open
    opener=self._opener)
  File "/om2/user/nlo/miniconda/envs/pydra/lib/python3.7/pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpiets1_f3/SlurmWorker_scripts/FunctionTask_08e96558d9f306ed8c5971146402d5d59df7a0b8d91ee02663a9bc3a0d9355c3/slurm-18061743.err'
============================================================================ short test summary info =============================================================================
FAILED pydra/engine/tests/test_submitter.py::test_wf_in_wf[slurm] - AttributeError: 'NoneType' object has no attribute 'errored'
=============================================================================== 1 failed in 14.09s ===============================================================================
```

Not sure if I'm missing something or if this is just a bug? 

Some other examples of tests with the same issue are
- `test_submitter.py` - `test_wf2`
-  `test_workflow.py` - all tests starting with `test_wfasnd_`

**Comment by djarecka** [comment]
@nicolocin - it looks like a bug, from what I see Slurm_Worker script might not be created in the right place

**Comment by djarecka** [comment]
I would think that if the main workflow has set `cache_dir` all other inner workflow should also have proper `cache_dir`, can you double check it

**Comment by djarecka** [comment]
but do they inherit the `cache_dir` on OSX?

**Comment by djarecka** [comment]
yes, so it is set during the run time

**Comment by djarecka** [comment]
it should be solved already, @nicolocin - please reopen if you still see it
