### ISSUE TITLE
Unable to run pydra workflow

### ISSUE THREAD

**Issue by andrewrosss** [nipype/pydra#450]
I'm trying to get started with a basic workflow and can't seem to get going. I feel like I probably just have something hooked up wrong. Here's a simplified script replicating the issue:

```python
from pathlib import Path
from typing import List

import pydra


@pydra.mark.task
def squares(nums: List[float]) -> float:
    return 0 if not nums else sum(n ** 2 for n in nums)


# create/hook up the workflow
cache_dir = Path("./cache").resolve()
wf = pydra.Workflow("sample_workflow", input_spec=["nums"], cache_dir=cache_dir)
wf.add(squares(name="sq", nums=wf.lzin.nums))
wf.set_output({"out": wf.sq.lzout.out})


# The various ways I've attempted to invoke the workflow:
# --------------------------------------------------


# Attempt 1: sanity check - the task in the workflow seems to run
# OK: Result(output=Output(out=30), runtime=None, errored=False)
task = squares(nums=[1, 2, 3, 4])
res = task()
print(res)


# Attempt 2: Since workflows are subclasses of tasks this was the first attempt
# TypeError: 'Result' object is not callable
task = wf(nums=[1, 2, 3, 4])
res = task()
print(res)


# Attempt 3: Calling the workflow directly (with inputs as kwargs)
# RuntimeError:
#         An attempt has been made to start a new process before the
#         current process has finished its bootstrapping phase.
#
#         This probably means that you are not using fork to start your
#         child processes and you have forgotten to use the proper idiom
#         in the main module:
#
#             if __name__ == '__main__':
#                 freeze_support()
#                 ...
#
#         The "freeze_support()" line can be omitted if the program
#         is not going to be frozen to produce an executable.
res = wf(nums=[1, 2, 3, 4])
print(res)


# Attempt 4: Calling the workflow directly ("externally" specifying inputs)
# RuntimeError: ... same as above
wf.inputs.nums = [1, 2, 3, 4]
res = wf()
print(res)


# Attempt 5: Running with an explicit submitter
# RuntimeError: ... same as above
with pydra.Submitter() as sub:
    wf.inputs.nums = [1, 2, 3, 4]
    res = sub(wf)
print(res)
```

It looks like the `TypeError` (Attempt 2) is expected bahaviour because the semantics for calling workflows appear to be different than tasks? (But maybe I have that wrong.)

I'm not sure what's causing the runtime error (Attempts 3, 4, 5). The full traceback is:

```text
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<ConcurrentFuturesWorker.exec_as_coro() done, defined at /path/to/venv/lib/python3.9/site-packages/pydra/engine/workers.py:160> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/workers.py", line 163, in exec_as_coro
    res = await self.loop.run_in_executor(self.pool, runnable._run, rerun)
  File "/path/to/venv/lib/python3.9/asyncio/base_events.py", line 814, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/path/to/venv/lib/python3.9/concurrent/futures/process.py", line 697, in submit
    self._adjust_process_count()
  File "/path/to/venv/lib/python3.9/concurrent/futures/process.py", line 675, in _adjust_process_count
    p.start()
  File "/path/to/venv/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/path/to/venv/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/path/to/venv/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/path/to/venv/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/path/to/venv/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/path/to/venv/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/path/to/venv/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/venv/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/path/to/venv/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/path/to/venv/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/path/to/venv/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/path/to/venv/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/path/to/venv/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/path/to/venv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/path/to/t.py", line 49, in <module>
    res = wf(nums=[1, 2, 3, 4])
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/core.py", line 424, in __call__
    res = sub(self)
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/submitter.py", line 56, in __call__
    self.loop.run_until_complete(self.submit_workflow(runnable, rerun=rerun))
  File "/path/to/venv/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/submitter.py", line 71, in submit_workflow
    await workflow._run(self, rerun=rerun)
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/core.py", line 1002, in _run
    result.output = self._collect_outputs()
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/core.py", line 1088, in _collect_outputs
    val_out = val.get_value(self)
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/specs.py", line 793, in get_value
    if result.errored:
AttributeError: 'NoneType' object has no attribute 'errored'
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<ConcurrentFuturesWorker.exec_as_coro() done, defined at /path/to/venv/lib/python3.9/site-packages/pydra/engine/workers.py:160> exception=BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.')>
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/workers.py", line 163, in exec_as_coro
    res = await self.loop.run_in_executor(self.pool, runnable._run, rerun)
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "/path/to/t.py", line 49, in <module>
    res = wf(nums=[1, 2, 3, 4])
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/core.py", line 424, in __call__
    res = sub(self)
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/submitter.py", line 56, in __call__
    self.loop.run_until_complete(self.submit_workflow(runnable, rerun=rerun))
  File "/path/to/venv/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/submitter.py", line 71, in submit_workflow
    await workflow._run(self, rerun=rerun)
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/core.py", line 1002, in _run
    result.output = self._collect_outputs()
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/core.py", line 1088, in _collect_outputs
    val_out = val.get_value(self)
  File "/path/to/venv/lib/python3.9/site-packages/pydra/engine/specs.py", line 793, in get_value
    if result.errored:
AttributeError: 'NoneType' object has no attribute 'errored'
```

Some additional environment/runtime information:

```text
os = macOS Big Sur 11.2.3
python = 3.9
pydra = 0.14.1
```

**Comment by andrewrosss** [comment]
Hmm, so the plot thickens. It looks like the behavior changes with the version of python. Assuming the same workflow code as above (here again for convenience):

```python
from pathlib import Path
from typing import List

import pydra


@pydra.mark.task
def squares(nums: List[float]) -> float:
    return 0 if not nums else sum(n ** 2 for n in nums)


# create/hook up the workflow
cache_dir = Path("./cache").resolve()
wf = pydra.Workflow("sample_workflow", input_spec=["nums"], cache_dir=cache_dir)
wf.add(squares(name="sq", nums=wf.lzin.nums))
wf.set_output({"out": wf.sq.lzout.out})
```

I get the following behaviors depending on how the workflow is invoked:

```python
# Attempt 3
# python3.7: ValueError ... (below)
# python3.8: ValueError ...
res = wf(nums=[1, 2, 3, 4])
```

```python
# Attempt 4
# python3.7: OK!
# python3.8: RuntimeError ... (same as previous comment)
wf.inputs.nums = [1, 2, 3, 4]
res = wf()
```

```python
# Attempt 5
# python3.7: OK!
# python3.8: RuntimeError ... (same as previous comment)
with pydra.Submitter() as sub:
    wf.inputs.nums = [1, 2, 3, 4]
    res = sub(wf)
```

The exception mentioned in the first code block above:

```text
Task exception was never retrieved
future: <Task finished coro=<ConcurrentFuturesWorker.exec_as_coro() done, defined at /Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/site-packages/pydra/engine/workers.py:160> exception=TypeError("'_Nothing' object is not iterable")>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/site-packages/pydra/engine/core.py", line 463, in _run
    self._run_task()
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/site-packages/pydra/engine/task.py", line 199, in _run_task
    output = cp.loads(self.inputs._func)(**inputs)
  File "t.py", line 9, in squares
    return 0 if not nums else sum(n ** 2 for n in nums)
TypeError: '_Nothing' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/site-packages/pydra/engine/workers.py", line 163, in exec_as_coro
    res = await self.loop.run_in_executor(self.pool, runnable._run, rerun)
TypeError: '_Nothing' object is not iterable
Traceback (most recent call last):
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/site-packages/pydra/engine/core.py", line 1088, in _collect_outputs
    val_out = val.get_value(self)
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/site-packages/pydra/engine/specs.py", line 794, in get_value
    raise ValueError("Error from get_value")
ValueError: Error from get_value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t.py", line 44, in <module>
    res = wf(nums=[1, 2, 3, 4])
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/site-packages/pydra/engine/core.py", line 424, in __call__
    res = sub(self)
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/site-packages/pydra/engine/submitter.py", line 56, in __call__
    self.loop.run_until_complete(self.submit_workflow(runnable, rerun=rerun))
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/site-packages/pydra/engine/submitter.py", line 71, in submit_workflow
    await workflow._run(self, rerun=rerun)
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/site-packages/pydra/engine/core.py", line 1002, in _run
    result.output = self._collect_outputs()
  File "/Users/andrewross/Documents/sandbox/performancephenomics-x/grant-inovait-2021/venv37/lib/python3.7/site-packages/pydra/engine/core.py", line 1098, in _collect_outputs
    raise ValueError(f"Task {val.name} raised an error")
ValueError: Task sq raised an error
```

**Comment by satra** [comment]
@andrewrosss - looking into this, but i can't replicate the first error

```python
Python 3.9.4 (default, Apr  9 2021, 09:32:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pathlib import Path
   ...: from typing import List
   ...: 
   ...: import pydra
   ...: 
   ...: 
   ...: @pydra.mark.task
   ...: def squares(nums: List[float]) -> float:
   ...:     return 0 if not nums else sum(n ** 2 for n in nums)
   ...: 

In [2]: cache_dir = Path("./cache").resolve()
   ...: wf = pydra.Workflow("sample_workflow", input_spec=["nums"])
   ...: wf.add(squares(name="sq", nums=wf.lzin.nums))
   ...: wf.set_output({"out": wf.sq.lzout.out})

In [3]: wf.inputs.nums = [1, 2, 3, 4]

In [4]: res = wf()

In [5]: res
Out[5]: Result(output=Output(out=30), runtime=None, errored=False)

In [6]: pydra.__version__
Out[6]: '0.14.1'

```
note that is removed cached_dir - just so that it doesn't come into play immediately.

```
In [10]: wf.cache_dir = None

In [11]: res = wf(nums=[1, 2, 3, 4])

In [12]: res
Out[12]: Result(output=Output(out=30), runtime=None, errored=False)
```

i'm going to check some other variants.

**Comment by satra** [comment]
i can't replicate error 1 when i start with `res = wf(nums=[1, 2, 3, 4])`

**Comment by satra** [comment]
thank you for this exhaustive assessment. we are looking into it and will report back.

**Comment by djarecka** [comment]
#451 should fix the issue with `wf(nums=[1, 2, 3, 4])`. Could you give it a try? 

I'm also not able to recreate other errors. Could you perhaps change `cache_dir` (or just leave it empty so it will be created a temporary directory) and run again.

**Comment by andrewrosss** [comment]
Woah super fast response time!

@djarecka It looks like the changes in your branch for #451 make running the workflow with `wf(nums=[1, 2, 3, 4])` work for me as well.

Rergarding the other errors, it might have something to do with my setup. I think I might need to reinstall `conda` or something. I was getting those runtime errors regardless of: how I created the environment, `cache_dir` or no `cache_dir`, it seems like basically any env pointing at/or build from my installed conda pythons (3.8/3.9). 

But running with `python3.8/3.9` in a fresh docker container seems to make everything work (no more RuntimeError). Makes me think it's not a pydra bug.

**Comment by djarecka** [comment]
ok, that's great! 

You could also always test pydra running tests `pytest -vs pydra/engine/tests`. Closing the issue, feel free to open a new one in case you have some issues
