### ISSUE TITLE
Rerun Errored Tasks

### ISSUE THREAD

**Issue by chasejohnson3** [nipype/pydra#482]
In Pydra, is it possible to rerun a workflow but only rerun the tasks that errored the first time the workflow was run?

I have a pipeline and sometimes tasks fail along the way. Rerunning with the same cache returns the same error because the error was cached. I would like to avoid rerunning the tasks that completed successfully and only rerun the failed tasks.

**Comment by satra** [comment]
this is bug and should not happen. errored runs should try rerunning. i would check the task run function to see if a fix is needed there.

if checksum and not errored.

**Comment by chasejohnson3** [comment]
I believe I have observed this behavior when a task is inside a workflow and the workflow caches the error. I will have to investigate further, but it is good to know rerunning errored tasks is the intended behavior.

**Comment by satra** [comment]
if the task errors inside a workflow. technically the workflow should error as well.

**Comment by chasejohnson3** [comment]
Yes, I am seeing the workflow erroring when a task inside errors. I will have to see if I can reproduce this bug.

**Comment by chasejohnson3** [comment]
I was able to reproduce the error. Please let me know if there is an error in my approach to this error, but if not, I will work on coming up with the solution.

Code used to reproduce error:
```
import pydra
import random


@pydra.mark.task
def pydra_random(x):
    rand = random.randint(0,1)
    if rand == 0:
        print(f"Rand = {rand} (error)")
        raise Exception("0 error")
    else:
        print(f"Rand = {rand}")
        return rand

task = pydra_random(name="pydra_random", x=[1, 2, 3, 4, 5], cache_dir="/Shared/sinapse/pydra-cjohnson/rerun_errored").split("x")

with pydra.Submitter("cf") as sub:
    sub(task)

print(task.result())
```

1st Output: 
```
Rand = 0 (error)
Rand = 1
Rand = 1
Rand = 0 (error)
Rand = 1
concurrent.futures.process._RemoteTraceback:
"""
Exception: 0 error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cjohnson30/anaconda3/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Shared/sinapse/pydra-cjohnson/pydra/pydra/engine/helpers.py", line 799, in load_and_run
    raise type(excinfo)(
Exception: ('0 error', ' full crash report is here: /Shared/sinapse/pydra-cjohnson/rerun_errored/FunctionTask_df3f1b43ae665778c6e5b4442141a3d70a17ce2a821fee53aaff09b966019fbf/_error.pklz')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rerun_errored.py", line 18, in <module>
    sub(task)
  File "/Shared/sinapse/pydra-cjohnson/pydra/pydra/engine/submitter.py", line 66, in __call__
    self.loop.run_until_complete(self.submit(runnable, wait=True, rerun=rerun))
  File "/Users/cjohnson30/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Shared/sinapse/pydra-cjohnson/pydra/pydra/engine/submitter.py", line 140, in submit
    await asyncio.gather(*futures)
  File "/Shared/sinapse/pydra-cjohnson/pydra/pydra/engine/workers.py", line 174, in exec_as_coro
    res = await self.loop.run_in_executor(
Exception: ('0 error', ' full crash report is here: /Shared/sinapse/pydra-cjohnson/rerun_errored/FunctionTask_df3f1b43ae665778c6e5b4442141a3d70a17ce2a821fee53aaff09b966019fbf/_error.pklz')
```

When I run this again, I would expect the 2 errored tasks to be rerun, but instead the results of each task are just recorded with some having `errored=True`:

2nd Output:
```
[Result(output=Output(out=1), runtime=None, errored=False), 
Result(output=Output(out=1), runtime=None, errored=False), 
Result(output=None, runtime=None, errored=True), 
Result(output=Output(out=1), runtime=None, errored=False),
Result(output=None, runtime=None, errored=True)]
```

**Comment by chasejohnson3** [comment]
After PR #483, it seemed errored tasks would be run again even if the result was stored in the cache. However, when a workflow splits on a list of inputs, only one errored element is run the second time. @satra Do you have any idea where this behavior may be coming from/how it could be corrected? I have been looking for a solution but haven't found one yet.

Code:
```
import pydra
import uuid
from pathlib import Path

@pydra.mark.task
def pass_odds(x):
    if x % 2 == 0:
        print(f"{x}%2 = {x % 2} (error)")
        raise Exception("even error")
    else:
        print(f"{x}%2 = {x % 2}")
        return x

wf = pydra.Workflow(
    name="wf",
    input_spec=["x"],
    x=[1, 2, 3, 4, 5, 6, 7, 8, 9],
    cache_dir= Path("./test") / Path(str(uuid.uuid4()))

).split("x")
wf.add(pass_odds(name="pass_odds", x=wf.lzin.x))
wf.set_output([("out", wf.pass_odds.lzout.out)])

print("First run")
try:
    wf()
    print(wf.result())
except:
    pass

print("Second run")
try:
    wf()
    print(wf.result())
except:
    pass
```

Actual Output:
```
First run
1%2 = 1
2%2 = 0 (error)
3%2 = 1
4%2 = 0 (error)
5%2 = 1
6%2 = 0 (error)
7%2 = 1
8%2 = 0 (error)
9%2 = 1
Second run
4%2 = 0 (error)

ERRORS OUT with `Exception: even error`
```


Expected Output:
```
First run
1%2 = 1
2%2 = 0 (error)
3%2 = 1
4%2 = 0 (error)
5%2 = 1
6%2 = 0 (error)
7%2 = 1
8%2 = 0 (error)
9%2 = 1
Second run
2%2 = 0 (error)
4%2 = 0 (error)
6%2 = 0 (error)
8%2 = 0 (error)
```

**Comment by chasejohnson3** [comment]
I believe the above comment above is related to a separate issue with workflows being stopped by an exception popping up within the workflow. I am going to make a separate issue to address it.
